version: "2.1"

services:

  gradle-embedded-cassandra-server-app:
    build:
      context: .
      dockerfile: gradle/Dockerfile
    volumes: ["gradle-embedded-cassandra-server-app-data:/home/appuser"]
    ports:
    - "8080:8080"
    - "9042:9042"
    networks: [backing-services]

volumes:
  gradle-embedded-cassandra-server-app-data: {}

networks:
  backing-services:
    driver: bridge
