version: '2.1'

services:

  cassandra:
    build:
      context: .
      dockerfile: gradle/Dockerfile
    volumes: ['data:/home/cassandra']
    ports:
    - '8080:8080'
    - '9042:9042'
    networks: [backing-services]

volumes:
  data: {}

networks:
  backing-services:
    driver: bridge
