cassandra:
  port: 9042
  keyspace: demo
  clean-data-files-at-startup: true

#spring:
#  data:
#    cassandra:
#      keyspace-name: ${cassandra.keyspace}
#
#management:
#  health:
#    cassandra:
#      enabled: true
